DROP DATABASE db_asistencia;
-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 09:54:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_asistencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_asistencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_asistencia` DEFAULT CHARACTER SET utf8 ;
USE `db_asistencia` ;

-- -----------------------------------------------------
-- Table `db_asistencia`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asistencia`.`ROLES` (
  `rol_code` INT NOT NULL AUTO_INCREMENT,
  `rol_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`rol_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_asistencia`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asistencia`.`USERS` (
  `rol_code` INT NOT NULL,
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NOT NULL,
  `user_email` VARCHAR(100) NOT NULL,
  `user_pass` VARCHAR(200) NOT NULL,
  `user_state` TINYINT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `ind_users_roles` (`rol_code` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`rol_code`)
    REFERENCES `db_asistencia`.`ROLES` (`rol_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_asistencia`.`ESTUDIANTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asistencia`.`ESTUDIANTES` (
  `estudiante_id` INT NOT NULL,
  `estudiante_grado` VARCHAR(45) NULL,
  `estudiante_jornada` VARCHAR(45) NULL,
  PRIMARY KEY (`estudiante_id`),
  INDEX `ind_estudiante_users` (`estudiante_id` ASC),
  CONSTRAINT `fk_estudiante_users`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `db_asistencia`.`USERS` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_asistencia`.`ESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asistencia`.`ESTADO` (
  `estado_id` INT NOT NULL,
  `estado_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`estado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_asistencia`.`ASISTENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asistencia`.`ASISTENCIA` (
  `estudiante_id` INT NULL,
  `estado_id` INT NULL,
  `asistencia_fecha` VARCHAR(45) NULL,
  `asistencia_hora_inicio` VARCHAR(45) NULL,
  INDEX `ind_asistencia_estudiante` (`estudiante_id` ASC),
  INDEX `ind_asistencia_estado` (`estado_id` ASC),
  CONSTRAINT `fk_asistencia_estudiante`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `db_asistencia`.`ESTUDIANTES` (`estudiante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asistencia_estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `db_asistencia`.`ESTADO` (`estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_asistencia`.`ACUDIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asistencia`.`ACUDIENTES` (
  `acudiente_id` INT NOT NULL,
  PRIMARY KEY (`acudiente_id`),
  INDEX `ind_acudiente_users` (`acudiente_id` ASC),
  CONSTRAINT `fk_acudiente_users`
    FOREIGN KEY (`acudiente_id`)
    REFERENCES `db_asistencia`.`USERS` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_asistencia`.`ACUDIENTES_ESTUDIANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asistencia`.`ACUDIENTES_ESTUDIANTE` (
  `acudiente_id` INT NOT NULL,
  `estudiante_id` INT NOT NULL,
  INDEX `ind_acudiente_acudiente` (`acudiente_id` ASC),
  INDEX `ind_acudiente_estudiante` (`estudiante_id` ASC),
  CONSTRAINT `fk_acudiente_acudiente`
    FOREIGN KEY (`acudiente_id`)
    REFERENCES `db_asistencia`.`ACUDIENTES` (`acudiente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acudiente_estudiante`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `db_asistencia`.`ESTUDIANTES` (`estudiante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_asistencia`.`PROFESORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asistencia`.`PROFESORES` (
  `profesor_id` INT NOT NULL,
  PRIMARY KEY (`profesor_id`),
  INDEX `ind_profesor_user` (`profesor_id` ASC),
  CONSTRAINT `fk_profesor_user`
    FOREIGN KEY (`profesor_id`)
    REFERENCES `db_asistencia`.`USERS` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_asistencia`.`JUSTIFICACIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_asistencia`.`JUSTIFICACIONES` (
  `profesor_id` INT NOT NULL,
  `estudiante_id` INT NOT NULL,
  `acudiente_id` INT NOT NULL,
  `justificacion_id` INT NOT NULL,
  `jusificacion_descripcion` VARCHAR(45) NOT NULL,
  `justificacion_validacion` TINYINT NOT NULL,
  PRIMARY KEY (`justificacion_id`),
  INDEX `ind_just_prof` (`profesor_id` ASC),
  INDEX `ind_just_acu` (`profesor_id` ASC),
  INDEX `ind_just_acud_idx` (`acudiente_id` ASC),
  INDEX `ind_just_asis` (`estudiante_id` ASC),
  CONSTRAINT `fk_just_prof`
    FOREIGN KEY (`profesor_id`)
    REFERENCES `db_asistencia`.`PROFESORES` (`profesor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_just_acud`
    FOREIGN KEY (`acudiente_id`)
    REFERENCES `db_asistencia`.`ACUDIENTES` (`acudiente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jusf_asis`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `db_asistencia`.`ASISTENCIA` (`estudiante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
