-- MySQL Script generated by MySQL Workbench
-- Wed Jun 19 10:01:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_assistance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_assistance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_assistance` DEFAULT CHARACTER SET utf8 ;
USE `db_assistance` ;

-- -----------------------------------------------------
-- Table `db_assistance`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_assistance`.`ROLES` (
  `rol_id` INT NOT NULL AUTO_INCREMENT,
  `rol_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_assistance`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_assistance`.`USERS` (
  `user_id` VARCHAR(20) NOT NULL,
  `rol_id` INT NOT NULL,
  `user_name` VARCHAR(200) NOT NULL,
  `user_email` VARCHAR(200) NULL,
  `user_pass` VARCHAR(200) NOT NULL,
  `user_state` TINYINT NOT NULL,
  INDEX `ind_user_rol` (`rol_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `db_assistance`.`ROLES` (`rol_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_assistance`.`STUDENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_assistance`.`STUDENTS` (
  `student_id` VARCHAR(20) NOT NULL,
  `student_workdays` VARCHAR(20) NOT NULL,
  `student_grade` VARCHAR(20) NOT NULL,
  `student_group` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `fk_student_user`
    FOREIGN KEY (`student_id`)
    REFERENCES `db_assistance`.`USERS` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_assistance`.`ASSISTANCES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_assistance`.`ASSISTANCES` (
  `student_id` VARCHAR(20) NOT NULL,
  `assistance_attends` VARCHAR(20) NOT NULL,
  `assistance_date` DATE NULL,
  `assistance_start_time` TIME NULL,
  INDEX `ind_assistance_student` (`student_id` ASC) INVISIBLE,
  CONSTRAINT `fk_assistance_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `db_assistance`.`STUDENTS` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_assistance`.`ATTENDANTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_assistance`.`ATTENDANTS` (
  `attendant_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`attendant_id`),
  CONSTRAINT `fk_attendant_user`
    FOREIGN KEY (`attendant_id`)
    REFERENCES `db_assistance`.`USERS` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_assistance`.`ATTENDANTS_STUDENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_assistance`.`ATTENDANTS_STUDENTS` (
  `student_id` VARCHAR(20) NOT NULL,
  `attendant_id` VARCHAR(20) NOT NULL,
  INDEX `ind_attendant_student_student` (`student_id` ASC) VISIBLE,
  INDEX `ind_attendant_student_attendant` (`attendant_id` ASC) VISIBLE,
  CONSTRAINT `fk_attendant_student_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `db_assistance`.`STUDENTS` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_attendant_student_attendant`
    FOREIGN KEY (`attendant_id`)
    REFERENCES `db_assistance`.`ATTENDANTS` (`attendant_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_assistance`.`TEACHERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_assistance`.`TEACHERS` (
  `teacher_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`teacher_id`),
  CONSTRAINT `fk_teacher_user`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `db_assistance`.`USERS` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_assistance`.`JUSTIFICATIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_assistance`.`JUSTIFICATIONS` (
  `student_id` VARCHAR(20) NULL,
  `attendant_id` VARCHAR(20) NULL,
  `teacher_id` VARCHAR(20) NULL,
  `justification_description` VARCHAR(45) NOT NULL,
  `justification_evidence` VARCHAR(200) NOT NULL,
  `justification_validation` TINYINT NOT NULL,
  INDEX `ind_justification_teacher` (`teacher_id` ASC) INVISIBLE,
  INDEX `ind_justification_attendant` (`attendant_id` ASC) INVISIBLE,
  INDEX `ind_justification_assistance` (`student_id` ASC) INVISIBLE,
  CONSTRAINT `fk_justification_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `db_assistance`.`TEACHERS` (`teacher_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_justification_attendant`
    FOREIGN KEY (`attendant_id`)
    REFERENCES `db_assistance`.`ATTENDANTS` (`attendant_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_justification_assistance`
    FOREIGN KEY (`student_id`)
    REFERENCES `db_assistance`.`ASSISTANCES` (`student_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
